INTERVAL_GET_HUMIDEX_FROM_SENSOR_MIN = 10 
INTERVAL_SQUEEZE_HUMID_FROM_SHALLOW_CACHE_H = 1
INTERVAL_HUMIDEX_UPDATOR_SCHEDULER_SLEEP_S = 10
INTERVAL_FLUSH_CACHE_TO_DB_H = 2
DB_FILE_PATH = "/home/osmc/NAS/DB/humidex.csv"
