INTERVAL_GET_HUMIDEX_FROM_SENSOR_MIN = 3
INTERVAL_SQUEEZE_HUMID_FROM_SHALLOW_CACHE_H = 0.16  # 10min
INTERVAL_HUMIDEX_UPDATOR_SCHEDULER_SLEEP_S = 0.5
INTERVAL_FLUSH_CACHE_TO_DB_H = 2
DB_FILE_PATH = "/home/osmc/NAS/DB/humidex.csv"
ADAFRUIT_LIB_PATH = "/home/osmc/libs/" + \
    "Adafruit_Python_DHT/examples/AdafruitDHT.py"
