INTERVAL_GET_HUMIDEX_FROM_SENSOR_MIN = 10
INTERVAL_SQUEEZE_HUMID_FROM_SHALLOW_CACHE_H = 1
INTERVAL_HUMIDEX_UPDATOR_SCHEDULER_SLEEP_S = 30
INTERVAL_FLUSH_CACHE_TO_DB_H = 3

INTERVAL_REFRESH_WUNDERLIST_TASKS_MIN = 2

DB_FILE_PATH = "/home/osmc/db/humidex.csv"
ADAFRUIT_LIB_PATH = "/home/osmc/libs/" + \
    "Adafruit_Python_DHT/examples/AdafruitDHT.py"